name: monitor-dashboard
services:
- name: web
  github:
    branch: master
    deploy_on_push: true
    repo: AyltonJunior/monitor-dashboard
  build_command: |
    npm ci
    npm run build
  run_command: npm run preview
  environment_slug: node-js
  instance_size_slug: basic-xxs
  instance_count: 1
  http_port: 8080
  static_sites:
  - name: client
    environment_slug: node-js
    github:
      repo: AyltonJunior/monitor-dashboard
      branch: master
      deploy_on_push: true
    output_dir: dist
    catchall_document: index.html
    routes:
      - path: /
  routes:
  - path: /
  envs:
  - key: VITE_FIREBASE_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_AUTH_DOMAIN
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_PROJECT_ID
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_STORAGE_BUCKET
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_MESSAGING_SENDER_ID
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_APP_ID
    scope: RUN_TIME
    type: SECRET
  - key: VITE_FIREBASE_DATABASE_URL
    scope: RUN_TIME
    type: SECRET
